@MinimalApiPractice_HostAddress = https://localhost:7149

POST {{MinimalApiPractice_HostAddress}}/todo
Content-Type: application/json

{
  "name":"Я ломал стекло",
  "description":"Не, хуня",
  "isDone":true
}
###

GET {{MinimalApiPractice_HostAddress}}/todos
Content-Type: application/json

###

GET {{MinimalApiPractice_HostAddress}}/todos/{id}

###
